kind: pipeline
name: default

steps:
  - name: build_pr
    image: docker
    commands:
      - docker build --build-arg NOTIFO__VERSION=3.0.0-$${DRONE_BUILD_NUMBER} .
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      NUGET_KEY:
        from_secret: NUGET_KEY
    when:
      event:
        - pull_request
      branch:
        - main
 
  - name: build_sdk
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - cd backend/sdk/
      - dotnet pack Notifo.SDK/Notifo.SDK.csproj --configuration Release
      - dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k $${NUGET_KEY}
    environment:
      NUGET_KEY:
        from_secret: NUGET_KEY
    when:
      event:
        - push
      branch:
        - main

  - name: build_dev
    image: docker
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t notifo --build-arg NOTIFO__VERSION=1.0.0-$${DRONE_BUILD_NUMBER} .
      - docker tag notifo squidex/notifo:latest
      - docker tag notifo squidex/notifo:1
      - docker tag notifo squidex/notifo:dev-$${DRONE_BUILD_NUMBER}
      - docker push squidex/notifo:latest
      - docker push squidex/notifo:1
      - docker push squidex/notifo:dev-$${DRONE_BUILD_NUMBER}
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      NUGET_KEY:
        from_secret: NUGET_KEY
    when:
      event:
        - push
      branch:
        - main
      
volumes:
  - name: docker1
    host:
      path: /var/run/docker.sock
  - name: docker2
    host:
      path: /var/lib/docker