<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <RootNamespace>Notifo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meziantou.Analyzer" Version="3.0.259">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MongoDB.Driver" Version="3.11.2" />
    <PackageReference Include="MongoDB.Driver.Core.Extensions.DiagnosticSources" Version="3.0.0" />
    <PackageReference Include="RefactoringEssentials" Version="5.6.0" PrivateAssets="all" />
    <PackageReference Include="Squidex.Assets.Mongo" Version="8.0.4" />
    <PackageReference Include="Squidex.OpenIddict.MongoDb" Version="7.2.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Notifo.Domain\Notifo.Domain.csproj" />
    <ProjectReference Include="..\Notifo.Identity\Notifo.Identity.csproj" />
    <ProjectReference Include="..\Notifo.Infrastructure\Notifo.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>
