/*
 * Notifo.io
 *
 * @license
 * Copyright (c) Sebastian Stehle. All rights reserved.
 */

/* eslint sort-keys-fix/sort-keys-fix: "error" */

export const EN = {
    app: {
        allowEmail: 'Allow Emails',
        allowSms: 'Allow SMS',
        apiDetails: 'Your API Credentials',
        apiKey: 'API Key',
        confirmUrl: 'Confirm URL',
        emailSettings: 'Email Settings',
        emailVerificationHint: 'You will receive an email from Amazon shortly to verify your email address. Please click the link in the email',
        firebaseCredential: 'Credential',
        firebaseProject: 'Project',
        firebaseSettings: 'Firebase Settings',
        smsSettings: 'SMS Settings',
        urls: 'URL Settings',
        webhookUrl: 'Webhook URL',
        welcome: (app: string) => `Welcome to the ${app} App`,
    },
    apps: {
        createButton: 'New App',
        createHeader: 'Create new App',
        header: 'Apps',
        notFound: 'App not found',
    },
    code: 'en',
    common: {
        actions: 'Actions',
        add: 'Add',
        appId: 'Application ID',
        apps: 'Apps',
        attempt: 'Attempts',
        back: 'Back',
        cancel: 'Cancel',
        channels: 'Channels',
        code: 'Code',
        confirm: 'Confirm',
        confirmMode: 'Confirm Mode',
        confirmModes: {
            explicit: 'Explicit',
            none: 'None',
        },
        confirmText: 'Confirm Text',
        contributors: 'Contributors',
        count: 'Count',
        create: 'Create',
        created: 'Created',
        dangerZone: 'Danger Zone',
        dashboard: 'Home',
        data: 'Data',
        delete: 'Delete',
        demo: 'Demo',
        design: 'Design',
        device: 'Device',
        disabled: 'Disabled',
        edit: 'Edit',
        email: 'Email',
        emailAddress: 'Email Address',
        emailName: 'Email Name',
        emailPlaceholder: 'name@my-site.com',
        emailTemplate: 'Email Template',
        emailVerificationStatus: 'Email verification',
        emails: 'Emails',
        enabled: 'Enabled',
        error: 'Error has occurred',
        failed: 'Failed',
        firstSeen: 'First seen',
        formatting: 'Formatting',
        html: 'HTML',
        id: 'Id',
        imageLarge: 'Large Image',
        imageSmall: 'Small Image',
        invite: 'Invite',
        inviteByEmail: 'Enter email-address to add contributor.',
        language: 'Language',
        languages: 'Languages',
        lastSeen: 'Last seen',
        lastUpdate: 'Last Update',
        lastWakeup: 'Last Wakeup',
        linkText: 'Link Text',
        linkUrl: 'Link URL',
        loading: 'Loading',
        logout: 'Logout',
        message: 'Message',
        messageBody: 'Body',
        messageSubject: 'Subject',
        mobilePush: 'Mobile',
        mode: 'Mode',
        more: 'More',
        name: 'Name',
        no: 'No',
        noName: 'Unnamed',
        notStarted: 'Not started',
        notYet: 'Not yet',
        notificationSettings: 'Notification Settings',
        notifications: 'Notifications',
        pagination: (start: number, end: number, total: number) => `${start} to ${end} of ${total}`,
        pending: 'Pending',
        phoneNumber: 'Phone Number',
        primary: 'Primary',
        prio: 'Prio',
        profile: 'Profile',
        publish: 'Publish',
        refresh: 'Refresh',
        sampleSubject: '-- No Subject yet --',
        save: 'Save',
        select: 'Select',
        send: 'Send',
        sendModes: {
            doNotAllow: 'Do not allow',
            doNotSend: 'Do not send',
            inherit: 'Inherit',
            send: 'Send',
        },
        sent: 'Sent',
        settings: 'Settings',
        showDetails: 'Show details',
        silent: 'Silent',
        sms: 'SMS',
        smsTemplate: 'SMS Template',
        statisticsInfo: 'Updated every 5 seconds (needs refresh)',
        statisticsLabelFn: (name: string) => `${name} (Handled / Attempts / Failed)`,
        status: 'Status',
        subject: 'Subject',
        template: 'Template',
        templateCode: 'Template Code',
        templateMode: 'Use template?',
        templates: 'Templates',
        text: 'Text',
        threemaId: 'Threema ID',
        timeToLive: 'Time to live in seconds',
        timestamp: 'Timestamp',
        timezone: 'Timezone',
        token: 'Token',
        topic: 'Topic',
        unnamed: 'Unnamed',
        uploadButton: 'Select file(s)',
        uploadText: 'Drop file on existing item to replace the asset with a newer version.',
        urlPlaceholder: 'https://my-site.com/path',
        users: 'Users',
        verified: 'Verified',
        webPlugin: 'Web Plugin',
        webPluginHint: 'Integrate Notifo into your Web application using our Plugin',
        webPush: 'Web Push',
        welcome: 'Welcome',
        yes: 'Yes',
    },
    emailTemplates: {
        bodyHtml: 'HTML Body',
        bodyHtmlValid: 'HTML Body is required and must be a valid template',
        bodyText: 'Text Body',
        bodyTextValid: 'Text Body is required and must be a valid template',
        confirmDelete: 'Do you really want to delete the Template?',
        create: 'Create',
        header: 'Email Templates',
        name: 'Template Name',
        notFound: 'No email template found',
        notFoundButton: 'Create template',
        notFoundLanguage: 'No Email template found for this language.',
        subjectValid: 'Subject is required and must be a valid template',
    },
    events: {
        eventsNotFound: 'No matching event found',
        header: 'Events',
        searchPlaceholder: 'Search',
    },
    integrations: {
        configured: 'Configured',
        confirmDelete: 'Do you really want to delete the Integration?',
        enabledHints: 'Disable the ingration without deleting it.',
        header: 'Integrations',
        modeProduction: 'PROD',
        modeTest: 'TEST',
        priority: 'Priority',
        priorityHints: 'Define a priority when you have configured multiple integrations for the same channel such as MobilePush.',
        supported: 'Supported',
        test: 'Test Mode',
        testHints: 'Use this integration only for production or development mode.',
    },
    log: {
        header: 'Log',
        logEntriesNotFound: 'No matching log entry found',
        searchPlaceholder: 'Search',
    },
    media: {
        confirmDelete: 'Do you really want to delete the Media?',
        header: 'Media',
        mediaNotFound: 'No matching media found',
        searchPlaceholder: 'Search',
    },
    messagingTemplates: {
        confirmDelete: 'Do you really want to delete the Template?',
        create: 'Create',
        header: 'Messaging Templates',
        name: 'Template Name',
        notFound: 'No Messaging template found',
        notFoundButton: 'Create template',
        singleHeader: 'Messaging Template',
    },
    notificationSettings: {
        delayInSeconds: 'Delay in seconds',
        email: {
            name: 'Email',
            send: 'Send as Email',
            title: 'Email',
        },
        messaging: {
            name: 'Messaging',
            send: 'Send using Messaging (Threema, ...)',
            title: 'Messaging',
        },
        mobilepush: {
            name: 'Mobile Push',
            send: 'Send as Mobile Push',
            title: 'Mobile Push',
        },
        sms: {
            name: 'SMS',
            send: 'Send as SMS',
            title: 'SMS',
        },
        webhook: {
            name: 'Webhook',
            send: 'Send to another Server',
            title: 'Webhook',
        },
        webpush: {
            name: 'Web Push',
            send: 'Send as Web Push',
            title: 'Web Push',
        },
    },
    notifications: {
        header: 'Notifications',
        notificationsNotFound: 'No matching notifications found',
        searchPlaceholder: 'Search',
    },
    publish: {
        header: 'Publish',
        success: 'Event has been published.',
    },
    smsTemplates: {
        confirmDelete: 'Do you really want to delete the Template?',
        create: 'Create',
        header: 'SMS Templates',
        name: 'Template Name',
        notFound: 'No SMS template found',
        notFoundButton: 'Create template',
        singleHeader: 'SMS Template',
    },
    subscriptions: {
        confirmDelete: 'Do you really want to delete the Subscription?',
        createButton: 'Subscribe',
        createHeader: 'Create new Subscription',
        editHeader: 'Edit Subscription',
        header: 'Subscriptions',
        searchPlaceholder: 'Search',
        subscriptionsNotFound: 'No matching subscriptions found',
    },
    templates: {
        confirmDelete: 'Do you really want to delete the Template?',
        createButton: 'New',
        header: 'Templates',
        templateEdit: 'Edit',
        templateNew: 'New Template',
        templatesNotFound: 'No matching template found',
    },
    users: {
        confirmDelete: 'Do you really want to delete the User?',
        createButton: 'New User',
        createHeader: 'Create new User',
        editHeader: 'Edit User',
        header: 'Users',
        searchPlaceholder: 'Search',
        userDetails: 'User Details',
        userNotFound: 'User not found',
        usersNotFound: 'No matching user found',
    },
    validation: {
        atLeastOnString: (p: { label?: string }) => `${p.label} needs at least one value.`,
        emailFn: (p: { label?: string }) => `${p.label} must be a valid email address.`,
        lessFn: (p: { label?: string; max: number }) => `${p.label} must be less than ${p.max}.`,
        lessThanFn: (p: { label?: string; less: number }) => `${p.label} must be less than ${p.less || 0}.`,
        minFn: (p: { label?: string; min: number }) => `${p.label} must have more than ${p.min || 0} items.`,
        moreFn: (p: { label?: string; min: number }) => `${p.label} must be greater than ${p.min}.`,
        moreThanFn: (p: { label?: string; more: number }) => `${p.label} must be greater than ${p.more || 0}.`,
        requiredFn: (p: { label?: string }) => `${p.label} is required.`,
        topicFn: (p: { label?: string }) => `${p.label} must be a valid topic.`,
        urlFn: (p: { label?: string }) => `${p.label} must be a valid URL.`,
    },
};
