//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifo.Domain.Integrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifo.Domain.Integrations.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not an allowed value..
        /// </summary>
        internal static string IntegrationPropertyAllowedValue {
            get {
                return ResourceManager.GetString("IntegrationPropertyAllowedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid boolean value..
        /// </summary>
        internal static string IntegrationPropertyInvalidBoolean {
            get {
                return ResourceManager.GetString("IntegrationPropertyInvalidBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number..
        /// </summary>
        internal static string IntegrationPropertyInvalidNumber {
            get {
                return ResourceManager.GetString("IntegrationPropertyInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have less than {0} characters..
        /// </summary>
        internal static string IntegrationPropertyMaxLength {
            get {
                return ResourceManager.GetString("IntegrationPropertyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be lower than {0}..
        /// </summary>
        internal static string IntegrationPropertyMaxValue {
            get {
                return ResourceManager.GetString("IntegrationPropertyMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have more than {0} characters..
        /// </summary>
        internal static string IntegrationPropertyMinLength {
            get {
                return ResourceManager.GetString("IntegrationPropertyMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be higher than {0}..
        /// </summary>
        internal static string IntegrationPropertyMinValue {
            get {
                return ResourceManager.GetString("IntegrationPropertyMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not a boolean..
        /// </summary>
        internal static string IntegrationPropertyNotBoolean {
            get {
                return ResourceManager.GetString("IntegrationPropertyNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not a number..
        /// </summary>
        internal static string IntegrationPropertyNotNumber {
            get {
                return ResourceManager.GetString("IntegrationPropertyNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is not a string type..
        /// </summary>
        internal static string IntegrationPropertyNotString {
            get {
                return ResourceManager.GetString("IntegrationPropertyNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field format not valid..
        /// </summary>
        internal static string IntegrationPropertyPattern {
            get {
                return ResourceManager.GetString("IntegrationPropertyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        internal static string IntegrationPropertyRequired {
            get {
                return ResourceManager.GetString("IntegrationPropertyRequired", resourceCulture);
            }
        }
    }
}
