//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifo.Domain.Integrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifo.Domain.Integrations.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the integrated Amazon Simple Email Service (SES) to send emails..
        /// </summary>
        internal static string AmazonSES_Description {
            get {
                return ResourceManager.GetString("AmazonSES_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Name.
        /// </summary>
        internal static string AmazonSES_FromEmailLabel {
            get {
                return ResourceManager.GetString("AmazonSES_FromEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email.
        /// </summary>
        internal static string AmazonSES_FromNameLabel {
            get {
                return ResourceManager.GetString("AmazonSES_FromNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon SES (Integrated).
        /// </summary>
        internal static string AmazonSES_Name {
            get {
                return ResourceManager.GetString("AmazonSES_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials as JSON document..
        /// </summary>
        internal static string Firebase_CredentialsHints {
            get {
                return ResourceManager.GetString("Firebase_CredentialsHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Firebase_CredentialsLabel {
            get {
                return ResourceManager.GetString("Firebase_CredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Push notifications to iOS and Android devices using MessageBird..
        /// </summary>
        internal static string Firebase_Description {
            get {
                return ResourceManager.GetString("Firebase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebase.
        /// </summary>
        internal static string Firebase_Name {
            get {
                return ResourceManager.GetString("Firebase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID.
        /// </summary>
        internal static string Firebase_ProjectIdLabel {
            get {
                return ResourceManager.GetString("Firebase_ProjectIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        internal static string MessageBird_AccessKeyLabel {
            get {
                return ResourceManager.GetString("MessageBird_AccessKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagebird integration using custom Access Key..
        /// </summary>
        internal static string MessageBird_Description {
            get {
                return ResourceManager.GetString("MessageBird_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagebird.
        /// </summary>
        internal static string MessageBird_Name {
            get {
                return ResourceManager.GetString("MessageBird_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string MessageBird_PhoneNumberLabel {
            get {
                return ResourceManager.GetString("MessageBird_PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated Messagebird integration for SMS messages..
        /// </summary>
        internal static string MessageBirdIntegrated_Description {
            get {
                return ResourceManager.GetString("MessageBirdIntegrated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBird (Integrated).
        /// </summary>
        internal static string MessageBirdIntegrated_Name {
            get {
                return ResourceManager.GetString("MessageBirdIntegrated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails using a custom email server..
        /// </summary>
        internal static string SMTP_Description {
            get {
                return ResourceManager.GetString("SMTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Name.
        /// </summary>
        internal static string SMTP_FromEmailLabel {
            get {
                return ResourceManager.GetString("SMTP_FromEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email.
        /// </summary>
        internal static string SMTP_FromNameLabel {
            get {
                return ResourceManager.GetString("SMTP_FromNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string SMTP_HostLabel {
            get {
                return ResourceManager.GetString("SMTP_HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom SMTP Server.
        /// </summary>
        internal static string SMTP_Name {
            get {
                return ResourceManager.GetString("SMTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for your SMTP server..
        /// </summary>
        internal static string SMTP_PasswordHints {
            get {
                return ResourceManager.GetString("SMTP_PasswordHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SMTP_PasswordLabel {
            get {
                return ResourceManager.GetString("SMTP_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string SMTP_PortLabel {
            get {
                return ResourceManager.GetString("SMTP_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for your SMTP server..
        /// </summary>
        internal static string SMTP_UsernameHints {
            get {
                return ResourceManager.GetString("SMTP_UsernameHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SMTP_UsernameLabel {
            get {
                return ResourceManager.GetString("SMTP_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Identity.
        /// </summary>
        internal static string ThreemaSimple_ApiIdentityLabel {
            get {
                return ResourceManager.GetString("ThreemaSimple_ApiIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API authentication secret.
        /// </summary>
        internal static string ThreemaSimple_ApiSecretLabel {
            get {
                return ResourceManager.GetString("ThreemaSimple_ApiSecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send server-side encrypted messages using Threema..
        /// </summary>
        internal static string ThreemaSimple_Description {
            get {
                return ResourceManager.GetString("ThreemaSimple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threema.
        /// </summary>
        internal static string ThreemaSimple_Name {
            get {
                return ResourceManager.GetString("ThreemaSimple_Name", resourceCulture);
            }
        }
    }
}
