//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifo.Domain.Integrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifo.Domain.Integrations.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preconfigured Amazon Simple Email Service (SES) to send emails..
        /// </summary>
        internal static string AmazonSES_Description {
            get {
                return ResourceManager.GetString("AmazonSES_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon SES (Integrated).
        /// </summary>
        internal static string AmazonSES_Name {
            get {
                return ResourceManager.GetString("AmazonSES_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address {0} is already used by another app..
        /// </summary>
        internal static string AmazonSES_ReservedEmailAddress {
            get {
                return ResourceManager.GetString("AmazonSES_ReservedEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma or line-separated list of additional email-addresses.
        /// </summary>
        internal static string Email_AdditionalFromEmailsDescription {
            get {
                return ResourceManager.GetString("Email_AdditionalFromEmailsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Addresses.
        /// </summary>
        internal static string Email_AdditionalFromEmailsLabel {
            get {
                return ResourceManager.GetString("Email_AdditionalFromEmailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender email address..
        /// </summary>
        internal static string Email_FromEmailDescription {
            get {
                return ResourceManager.GetString("Email_FromEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email.
        /// </summary>
        internal static string Email_FromEmailLabel {
            get {
                return ResourceManager.GetString("Email_FromEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the sender..
        /// </summary>
        internal static string Email_FromNameDescription {
            get {
                return ResourceManager.GetString("Email_FromNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Name.
        /// </summary>
        internal static string Email_FromNameLabel {
            get {
                return ResourceManager.GetString("Email_FromNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials as JSON document..
        /// </summary>
        internal static string Firebase_CredentialsHints {
            get {
                return ResourceManager.GetString("Firebase_CredentialsHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Firebase_CredentialsLabel {
            get {
                return ResourceManager.GetString("Firebase_CredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Push notifications to iOS and Android devices using MessageBird..
        /// </summary>
        internal static string Firebase_Description {
            get {
                return ResourceManager.GetString("Firebase_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse credentials..
        /// </summary>
        internal static string Firebase_InvalidCredentials {
            get {
                return ResourceManager.GetString("Firebase_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebase.
        /// </summary>
        internal static string Firebase_Name {
            get {
                return ResourceManager.GetString("Firebase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project ID.
        /// </summary>
        internal static string Firebase_ProjectIdLabel {
            get {
                return ResourceManager.GetString("Firebase_ProjectIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send silent notifications to Android.
        /// </summary>
        internal static string Firebase_SilentAndroidDescription {
            get {
                return ResourceManager.GetString("Firebase_SilentAndroidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent (Android).
        /// </summary>
        internal static string Firebase_SilentAndroidLabel {
            get {
                return ResourceManager.GetString("Firebase_SilentAndroidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send silent notifications to iOS.
        /// </summary>
        internal static string Firebase_SilentIOSDescription {
            get {
                return ResourceManager.GetString("Firebase_SilentIOSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent (iOS).
        /// </summary>
        internal static string Firebase_SilentIOSLabel {
            get {
                return ResourceManager.GetString("Firebase_SilentIOSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string Mailchimp_ApiKeyLabel {
            get {
                return ResourceManager.GetString("Mailchimp_ApiKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails over Mailchimp..
        /// </summary>
        internal static string Mailchimp_Description {
            get {
                return ResourceManager.GetString("Mailchimp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email to &apos;{0}: {1}..
        /// </summary>
        internal static string Mailchimp_Error {
            get {
                return ResourceManager.GetString("Mailchimp_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email to &apos;{0}&apos;: No result provided..
        /// </summary>
        internal static string Mailchimp_ErrorUnknown {
            get {
                return ResourceManager.GetString("Mailchimp_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailchimp.
        /// </summary>
        internal static string Mailchimp_Name {
            get {
                return ResourceManager.GetString("Mailchimp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string Mailjet_ApiKeyLabel {
            get {
                return ResourceManager.GetString("Mailjet_ApiKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Secret.
        /// </summary>
        internal static string Mailjet_ApiSecretLabel {
            get {
                return ResourceManager.GetString("Mailjet_ApiSecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails over Mailjet..
        /// </summary>
        internal static string Mailjet_Description {
            get {
                return ResourceManager.GetString("Mailjet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email to &apos;{0}: {1}/{2}..
        /// </summary>
        internal static string Mailjet_Error {
            get {
                return ResourceManager.GetString("Mailjet_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email to &apos;{0}&apos;: No result provided..
        /// </summary>
        internal static string Mailjet_ErrorUnknown {
            get {
                return ResourceManager.GetString("Mailjet_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailjet.
        /// </summary>
        internal static string Mailjet_Name {
            get {
                return ResourceManager.GetString("Mailjet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        internal static string MessageBird_AccessKeyLabel {
            get {
                return ResourceManager.GetString("MessageBird_AccessKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagebird integration using custom Access Key..
        /// </summary>
        internal static string MessageBird_Description {
            get {
                return ResourceManager.GetString("MessageBird_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string MessageBird_Error {
            get {
                return ResourceManager.GetString("MessageBird_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;..
        /// </summary>
        internal static string MessageBird_ErrorUnknown {
            get {
                return ResourceManager.GetString("MessageBird_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagebird SMS.
        /// </summary>
        internal static string MessageBird_Name {
            get {
                return ResourceManager.GetString("MessageBird_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name as alternative to Phone Number.
        /// </summary>
        internal static string MessageBird_OriginatorNameDescription {
            get {
                return ResourceManager.GetString("MessageBird_OriginatorNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originator.
        /// </summary>
        internal static string MessageBird_OriginatorNameLabel {
            get {
                return ResourceManager.GetString("MessageBird_OriginatorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string MessageBird_PhoneNumberLabel {
            get {
                return ResourceManager.GetString("MessageBird_PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country specific phone numbers. Each line is one phone number..
        /// </summary>
        internal static string MessageBird_PhoneNumbersDescription {
            get {
                return ResourceManager.GetString("MessageBird_PhoneNumbersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Numbers.
        /// </summary>
        internal static string MessageBird_PhoneNumbersLabel {
            get {
                return ResourceManager.GetString("MessageBird_PhoneNumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        internal static string MessageBird_SendSmsLabel {
            get {
                return ResourceManager.GetString("MessageBird_SendSmsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send WhatsApp.
        /// </summary>
        internal static string MessageBird_SendWhatsAppLabel {
            get {
                return ResourceManager.GetString("MessageBird_SendWhatsAppLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID of the WhatsApp Channel..
        /// </summary>
        internal static string MessageBird_WhatsAppChannelIdDescription {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppChannelIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp Channel ID.
        /// </summary>
        internal static string MessageBird_WhatsAppChannelIdLabel {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppChannelIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the template. Must have one parameter that will be the actual notification text (usually the subject)..
        /// </summary>
        internal static string MessageBird_WhatsAppTemplateNameDescription {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppTemplateNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        internal static string MessageBird_WhatsAppTemplateNameLabel {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppTemplateNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template namespace. Can be found in the WhatsApp templates Manager of your Facebook Business account..
        /// </summary>
        internal static string MessageBird_WhatsAppTemplateNamespaceDescription {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppTemplateNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Namespace.
        /// </summary>
        internal static string MessageBird_WhatsAppTemplateNamespaceLabel {
            get {
                return ResourceManager.GetString("MessageBird_WhatsAppTemplateNamespaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preconfigured Messagebird integration for SMS messages..
        /// </summary>
        internal static string MessageBirdIntegrated_Description {
            get {
                return ResourceManager.GetString("MessageBirdIntegrated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageBird (Integrated).
        /// </summary>
        internal static string MessageBirdIntegrated_Name {
            get {
                return ResourceManager.GetString("MessageBirdIntegrated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messagebird WhatsApp.
        /// </summary>
        internal static string MessageBirdWhatsApp_Name {
            get {
                return ResourceManager.GetString("MessageBirdWhatsApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails using a custom email server..
        /// </summary>
        internal static string SMTP_Description {
            get {
                return ResourceManager.GetString("SMTP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email using SMTP: {0}.
        /// </summary>
        internal static string SMTP_Exception {
            get {
                return ResourceManager.GetString("SMTP_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string SMTP_HostLabel {
            get {
                return ResourceManager.GetString("SMTP_HostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom SMTP Server.
        /// </summary>
        internal static string SMTP_Name {
            get {
                return ResourceManager.GetString("SMTP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for your SMTP server..
        /// </summary>
        internal static string SMTP_PasswordHints {
            get {
                return ResourceManager.GetString("SMTP_PasswordHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SMTP_PasswordLabel {
            get {
                return ResourceManager.GetString("SMTP_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string SMTP_PortLabel {
            get {
                return ResourceManager.GetString("SMTP_PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username for your SMTP server..
        /// </summary>
        internal static string SMTP_UsernameHints {
            get {
                return ResourceManager.GetString("SMTP_UsernameHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SMTP_UsernameLabel {
            get {
                return ResourceManager.GetString("SMTP_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        internal static string Telegram_AccessKeyLabel {
            get {
                return ResourceManager.GetString("Telegram_AccessKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ID to identity the user in the chat with the bot. Will be set automatically..
        /// </summary>
        internal static string Telegram_ChatIdDescription {
            get {
                return ResourceManager.GetString("Telegram_ChatIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Chat ID.
        /// </summary>
        internal static string Telegram_ChatIdLabel {
            get {
                return ResourceManager.GetString("Telegram_ChatIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send messages using Telegram..
        /// </summary>
        internal static string Telegram_Description {
            get {
                return ResourceManager.GetString("Telegram_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        internal static string Telegram_Name {
            get {
                return ResourceManager.GetString("Telegram_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have found your user. You will receive notifications now..
        /// </summary>
        internal static string Telegram_UserLinked {
            get {
                return ResourceManager.GetString("Telegram_UserLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username in telegram..
        /// </summary>
        internal static string Telegram_UsernameDescription {
            get {
                return ResourceManager.GetString("Telegram_UsernameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Username.
        /// </summary>
        internal static string Telegram_UsernameLabel {
            get {
                return ResourceManager.GetString("Telegram_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot find your user. Please create a username and configure the username in your {0} account.
        ///
        ///When you have done this send me an /update command..
        /// </summary>
        internal static string Telegram_UserNotFound {
            get {
                return ResourceManager.GetString("Telegram_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the {0} bot. I will send you your notifications..
        /// </summary>
        internal static string Telegram_WelcomeMessage {
            get {
                return ResourceManager.GetString("Telegram_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key.
        /// </summary>
        internal static string Telekom_ApiKeyLabel {
            get {
                return ResourceManager.GetString("Telekom_ApiKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom integration for sending SMS messages..
        /// </summary>
        internal static string Telekom_Description {
            get {
                return ResourceManager.GetString("Telekom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Telekom_Error {
            get {
                return ResourceManager.GetString("Telekom_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;..
        /// </summary>
        internal static string Telekom_ErrorUnknown {
            get {
                return ResourceManager.GetString("Telekom_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom.
        /// </summary>
        internal static string Telekom_Name {
            get {
                return ResourceManager.GetString("Telekom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Telekom_PhoneNumberLabel {
            get {
                return ResourceManager.GetString("Telekom_PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Numbers.
        /// </summary>
        internal static string Telekom_PhoneNumbersLabel {
            get {
                return ResourceManager.GetString("Telekom_PhoneNumbersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Identity.
        /// </summary>
        internal static string ThreemaSimple_ApiIdentityLabel {
            get {
                return ResourceManager.GetString("ThreemaSimple_ApiIdentityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API authentication secret.
        /// </summary>
        internal static string ThreemaSimple_ApiSecretLabel {
            get {
                return ResourceManager.GetString("ThreemaSimple_ApiSecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send server-side encrypted messages using Threema..
        /// </summary>
        internal static string ThreemaSimple_Description {
            get {
                return ResourceManager.GetString("ThreemaSimple_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threema.
        /// </summary>
        internal static string ThreemaSimple_Name {
            get {
                return ResourceManager.GetString("ThreemaSimple_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account SID.
        /// </summary>
        internal static string Twilio_AccountSidLabel {
            get {
                return ResourceManager.GetString("Twilio_AccountSidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Token.
        /// </summary>
        internal static string Twilio_AuthTokenLabel {
            get {
                return ResourceManager.GetString("Twilio_AuthTokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilio integration for sending SMS messages..
        /// </summary>
        internal static string Twilio_Description {
            get {
                return ResourceManager.GetString("Twilio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string Twilio_Error {
            get {
                return ResourceManager.GetString("Twilio_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config. Cannot authenticate or find phone number..
        /// </summary>
        internal static string Twilio_ErrorInvalidConfig {
            get {
                return ResourceManager.GetString("Twilio_ErrorInvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send sms to &apos;{0}&apos;..
        /// </summary>
        internal static string Twilio_ErrorUnknown {
            get {
                return ResourceManager.GetString("Twilio_ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twilio.
        /// </summary>
        internal static string Twilio_Name {
            get {
                return ResourceManager.GetString("Twilio_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Twilio_PhoneNumberLabel {
            get {
                return ResourceManager.GetString("Twilio_PhoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a HTTP request to your server when a notification is confirmed by a User..
        /// </summary>
        internal static string Webhook_Description {
            get {
                return ResourceManager.GetString("Webhook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP method.
        /// </summary>
        internal static string Webhook_MethodHints {
            get {
                return ResourceManager.GetString("Webhook_MethodHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Webhook_MethodLabel {
            get {
                return ResourceManager.GetString("Webhook_MethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional name when defining a template..
        /// </summary>
        internal static string Webhook_NameHints {
            get {
                return ResourceManager.GetString("Webhook_NameHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Webhook_NameLabel {
            get {
                return ResourceManager.GetString("Webhook_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this webhook for all notifications..
        /// </summary>
        internal static string Webhook_SendAlwaysHints {
            get {
                return ResourceManager.GetString("Webhook_SendAlwaysHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send always.
        /// </summary>
        internal static string Webhook_SendAlwaysLabel {
            get {
                return ResourceManager.GetString("Webhook_SendAlwaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmed notifications to this webhook..
        /// </summary>
        internal static string Webhook_SendConfirmHints {
            get {
                return ResourceManager.GetString("Webhook_SendConfirmHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirm.
        /// </summary>
        internal static string Webhook_SendConfirmLabel {
            get {
                return ResourceManager.GetString("Webhook_SendConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all notification to this webhook..
        /// </summary>
        internal static string Webhook_SendNotificationsHints {
            get {
                return ResourceManager.GetString("Webhook_SendNotificationsHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Always.
        /// </summary>
        internal static string Webhook_SendNotificationsLabel {
            get {
                return ResourceManager.GetString("Webhook_SendNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to your server endpoint..
        /// </summary>
        internal static string Webhook_URLHints {
            get {
                return ResourceManager.GetString("Webhook_URLHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Webhook_URLLabel {
            get {
                return ResourceManager.GetString("Webhook_URLLabel", resourceCulture);
            }
        }
    }
}
