//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifo.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifo.Domain.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself..
        /// </summary>
        internal static string App_CannotRemoveYourself {
            get {
                return ResourceManager.GetString("App_CannotRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot update yourself..
        /// </summary>
        internal static string App_CannotUpdateYourself {
            get {
                return ResourceManager.GetString("App_CannotUpdateYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upsert app..
        /// </summary>
        internal static string Apps_UpsertFailed {
            get {
                return ResourceManager.GetString("Apps_UpsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user..
        /// </summary>
        internal static string Apps_UserNotFound {
            get {
                return ResourceManager.GetString("Apps_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find language {0} in template &apos;{1}&apos;..
        /// </summary>
        internal static string ChannelTemplate_LanguageNotFound {
            get {
                return ResourceManager.GetString("ChannelTemplate_LanguageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find template &apos;{0}&apos;..
        /// </summary>
        internal static string ChannelTemplate_NotFound {
            get {
                return ResourceManager.GetString("ChannelTemplate_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find named template {0}, falling back to primary..
        /// </summary>
        internal static string ChannelTemplate_ResolvedWithFallback {
            get {
                return ResourceManager.GetString("ChannelTemplate_ResolvedWithFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration has been removed..
        /// </summary>
        internal static string Email_ConfigReset {
            get {
                return ResourceManager.GetString("Email_ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template does not render notification subject, loop over notification and use &apos;{{ notification.subject }}&apos;..
        /// </summary>
        internal static string Email_TemplateLiquidInvalid {
            get {
                return ResourceManager.GetString("Email_TemplateLiquidInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template does not render notification subject, add &apos;{{ notification.subject }}&apos; to each template..
        /// </summary>
        internal static string Email_TemplateNormalInvalid {
            get {
                return ResourceManager.GetString("Email_TemplateNormalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template must have a default template for notifcations, add &apos;&lt;!-- START: NOTIFICATION --&gt;&apos;..
        /// </summary>
        internal static string Email_TemplateNormalNoItem {
            get {
                return ResourceManager.GetString("Email_TemplateNormalNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either template for text or html body must be defined..
        /// </summary>
        internal static string Email_TemplateUndefined {
            get {
                return ResourceManager.GetString("Email_TemplateUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template generates unknown error..
        /// </summary>
        internal static string EmailUnknownErrror {
            get {
                return ResourceManager.GetString("EmailUnknownErrror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration of type {0} does not exist..
        /// </summary>
        internal static string IntegrationNotFound {
            get {
                return ResourceManager.GetString("IntegrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration is not valid..
        /// </summary>
        internal static string IntegrationNotValid {
            get {
                return ResourceManager.GetString("IntegrationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number..
        /// </summary>
        internal static string IntegrationPropertyInvalidNumber {
            get {
                return ResourceManager.GetString("IntegrationPropertyInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have less than {0} characters..
        /// </summary>
        internal static string IntegrationPropertyMaxLength {
            get {
                return ResourceManager.GetString("IntegrationPropertyMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be lower than {0}..
        /// </summary>
        internal static string IntegrationPropertyMaxValue {
            get {
                return ResourceManager.GetString("IntegrationPropertyMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must have more than {0} characters..
        /// </summary>
        internal static string IntegrationPropertyMinLength {
            get {
                return ResourceManager.GetString("IntegrationPropertyMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be higher than {0}..
        /// </summary>
        internal static string IntegrationPropertyMinValue {
            get {
                return ResourceManager.GetString("IntegrationPropertyMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field format not valid..
        /// </summary>
        internal static string IntegrationPropertyPattern {
            get {
                return ResourceManager.GetString("IntegrationPropertyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        internal static string IntegrationPropertyRequired {
            get {
                return ResourceManager.GetString("IntegrationPropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor &apos;{{user}} been added to app &apos;{{app}}&apos;..
        /// </summary>
        internal static string NotificationContributorCreated {
            get {
                return ResourceManager.GetString("NotificationContributorCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor &apos;{{user}}&apos; been removed from app &apos;{{app}}&apos;..
        /// </summary>
        internal static string NotificationContributorRemoved {
            get {
                return ResourceManager.GetString("NotificationContributorRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New log message in app &apos;{{app}}&apos;: {{log}}..
        /// </summary>
        internal static string NotificationFirstLog {
            get {
                return ResourceManager.GetString("NotificationFirstLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        internal static string NotificationLink {
            get {
                return ResourceManager.GetString("NotificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{{code}}&apos; has been removed from app &apos;{{app}}&apos;..
        /// </summary>
        internal static string NotificationTemplateDeleted {
            get {
                return ResourceManager.GetString("NotificationTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{{code}}&apos; has been added or updated in app &apos;{{app}}&apos;..
        /// </summary>
        internal static string NotificationTemplateUpserted {
            get {
                return ResourceManager.GetString("NotificationTemplateUpserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos; has no subject..
        /// </summary>
        internal static string Template_NoSubject {
            get {
                return ResourceManager.GetString("Template_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has unsupported language &apos;{0}&apos;, using &apos;{1}&apos; instead..
        /// </summary>
        internal static string UserLanguage_NotValid {
            get {
                return ResourceManager.GetString("UserLanguage_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid language..
        /// </summary>
        internal static string ValidationLanguage {
            get {
                return ResourceManager.GetString("ValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid liquid template..
        /// </summary>
        internal static string ValidationLiquid {
            get {
                return ResourceManager.GetString("ValidationLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid phone number..
        /// </summary>
        internal static string ValidationPhoneNumber {
            get {
                return ResourceManager.GetString("ValidationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid role..
        /// </summary>
        internal static string ValidationRole {
            get {
                return ResourceManager.GetString("ValidationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid timezone..
        /// </summary>
        internal static string ValidationTimezone {
            get {
                return ResourceManager.GetString("ValidationTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid topic..
        /// </summary>
        internal static string ValidationTopic {
            get {
                return ResourceManager.GetString("ValidationTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid URL..
        /// </summary>
        internal static string ValidationUrl {
            get {
                return ResourceManager.GetString("ValidationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a HTTP request to your server when a notification is confirmed by a User..
        /// </summary>
        internal static string Webhook_Description {
            get {
                return ResourceManager.GetString("Webhook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HTTP method.
        /// </summary>
        internal static string Webhook_MethodHints {
            get {
                return ResourceManager.GetString("Webhook_MethodHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Webhook_MethodLabel {
            get {
                return ResourceManager.GetString("Webhook_MethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The optional name when defining a template..
        /// </summary>
        internal static string Webhook_NameHints {
            get {
                return ResourceManager.GetString("Webhook_NameHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Webhook_NameLabel {
            get {
                return ResourceManager.GetString("Webhook_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this webhook for all notifications..
        /// </summary>
        internal static string Webhook_SendAlwaysHints {
            get {
                return ResourceManager.GetString("Webhook_SendAlwaysHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send always.
        /// </summary>
        internal static string Webhook_SendAlwaysLabel {
            get {
                return ResourceManager.GetString("Webhook_SendAlwaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmed notifications to this webhook..
        /// </summary>
        internal static string Webhook_SendConfirmHints {
            get {
                return ResourceManager.GetString("Webhook_SendConfirmHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirm.
        /// </summary>
        internal static string Webhook_SendConfirmLabel {
            get {
                return ResourceManager.GetString("Webhook_SendConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all notification to this webhook..
        /// </summary>
        internal static string Webhook_SendNotificationsHints {
            get {
                return ResourceManager.GetString("Webhook_SendNotificationsHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Always.
        /// </summary>
        internal static string Webhook_SendNotificationsLabel {
            get {
                return ResourceManager.GetString("Webhook_SendNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to your server endpoint..
        /// </summary>
        internal static string Webhook_URLHints {
            get {
                return ResourceManager.GetString("Webhook_URLHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Webhook_URLLabel {
            get {
                return ResourceManager.GetString("Webhook_URLLabel", resourceCulture);
            }
        }
    }
}
