//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifo.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notifo.Domain.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove yourself..
        /// </summary>
        internal static string App_CannotRemoveYourself {
            get {
                return ResourceManager.GetString("App_CannotRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot update yourself..
        /// </summary>
        internal static string App_CannotUpdateYourself {
            get {
                return ResourceManager.GetString("App_CannotUpdateYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upsert app..
        /// </summary>
        internal static string Apps_UpsertFailed {
            get {
                return ResourceManager.GetString("Apps_UpsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user..
        /// </summary>
        internal static string Apps_UserNotFound {
            get {
                return ResourceManager.GetString("Apps_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: Integration has been removed..
        /// </summary>
        internal static string Email_ConfigReset {
            get {
                return ResourceManager.GetString("Email_ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template is invalid and does not render property..
        /// </summary>
        internal static string Email_TemplateInvalid {
            get {
                return ResourceManager.GetString("Email_TemplateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template must have a template for notifcations..
        /// </summary>
        internal static string Email_TemplateNoItem {
            get {
                return ResourceManager.GetString("Email_TemplateNoItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: Template not found anymore..
        /// </summary>
        internal static string Email_TemplateNotFound {
            get {
                return ResourceManager.GetString("Email_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either template for text or html body must be defined..
        /// </summary>
        internal static string Email_TemplateUndefined {
            get {
                return ResourceManager.GetString("Email_TemplateUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: User has been deleted before sending email..
        /// </summary>
        internal static string Email_UserDeleted {
            get {
                return ResourceManager.GetString("Email_UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: User has no email address anymore..
        /// </summary>
        internal static string Email_UserNoEmail {
            get {
                return ResourceManager.GetString("Email_UserNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event with this id has already been processed..
        /// </summary>
        internal static string Events_AlreadyProcessed {
            get {
                return ResourceManager.GetString("Events_AlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create event..
        /// </summary>
        internal static string Events_CreationFailed {
            get {
                return ResourceManager.GetString("Events_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has neither a subject nor a template code..
        /// </summary>
        internal static string Events_NoSubjectOrTemplateCode {
            get {
                return ResourceManager.GetString("Events_NoSubjectOrTemplateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has no subscriber..
        /// </summary>
        internal static string Events_NoSubscriber {
            get {
                return ResourceManager.GetString("Events_NoSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has no topic..
        /// </summary>
        internal static string Events_NoTopic {
            get {
                return ResourceManager.GetString("Events_NoTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging: Integration has been removed..
        /// </summary>
        internal static string Messaging_ConfigReset {
            get {
                return ResourceManager.GetString("Messaging_ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePush: Integration has been removed..
        /// </summary>
        internal static string MobilePush_ConfigReset {
            get {
                return ResourceManager.GetString("MobilePush_ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePush: Token has been removed..
        /// </summary>
        internal static string MobilePush_TokenRemoved {
            get {
                return ResourceManager.GetString("MobilePush_TokenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has already been processed..
        /// </summary>
        internal static string Notification_AlreadyProcessed {
            get {
                return ResourceManager.GetString("Notification_AlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has no existing app. It has probably been deleted..
        /// </summary>
        internal static string Notification_NoApp {
            get {
                return ResourceManager.GetString("Notification_NoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has no subject for user..
        /// </summary>
        internal static string Notification_NoSubject {
            get {
                return ResourceManager.GetString("Notification_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has no existing user. It has probably been deleted..
        /// </summary>
        internal static string Notification_NoUser {
            get {
                return ResourceManager.GetString("Notification_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS: Integration has been removed..
        /// </summary>
        internal static string Sms_ConfigReset {
            get {
                return ResourceManager.GetString("Sms_ConfigReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template &apos;{0}&apos; has no subject..
        /// </summary>
        internal static string Template_NoSubject {
            get {
                return ResourceManager.GetString("Template_NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has unsupported language &apos;{0}&apos;, using &apos;{1}&apos; instead..
        /// </summary>
        internal static string UserLanguage_NotValid {
            get {
                return ResourceManager.GetString("UserLanguage_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid language..
        /// </summary>
        internal static string ValidationLanguage {
            get {
                return ResourceManager.GetString("ValidationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid liquid template..
        /// </summary>
        internal static string ValidationLiquid {
            get {
                return ResourceManager.GetString("ValidationLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid phone number..
        /// </summary>
        internal static string ValidationPhoneNumber {
            get {
                return ResourceManager.GetString("ValidationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid role..
        /// </summary>
        internal static string ValidationRole {
            get {
                return ResourceManager.GetString("ValidationRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid timezone..
        /// </summary>
        internal static string ValidationTimezone {
            get {
                return ResourceManager.GetString("ValidationTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid topic..
        /// </summary>
        internal static string ValidationTopic {
            get {
                return ResourceManager.GetString("ValidationTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be a valid URL..
        /// </summary>
        internal static string ValidationUrl {
            get {
                return ResourceManager.GetString("ValidationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a HTTP request to your server when a notification is confirmed by a User..
        /// </summary>
        internal static string Webhook_Description {
            get {
                return ResourceManager.GetString("Webhook_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to your server endpoint..
        /// </summary>
        internal static string Webhook_URLHints {
            get {
                return ResourceManager.GetString("Webhook_URLHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Webhook_URLLabel {
            get {
                return ResourceManager.GetString("Webhook_URLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPush: Token does not exist anymore..
        /// </summary>
        internal static string WebPush_TokenRemoved {
            get {
                return ResourceManager.GetString("WebPush_TokenRemoved", resourceCulture);
            }
        }
    }
}
