name: Build and Push to Nuget

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
 
    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Pack
      run: |
        cd backend/sdk/Notifo.SDK && dotnet pack -c Release

    - name: Publish
      run: |
        cd backend/sdk/Notifo.SDK && dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.NUGET }} --no-symbols 1 
