name: Nuget Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 7.0.x

      - name: Pack
        run: |
          cd tools/sdk/Notifo.SDK && dotnet pack -c Release

      - name: Publish
        run: |
          cd tools/sdk/Notifo.SDK && dotnet nuget push **/*.nupkg --source 'https://api.nuget.org/v3/index.json' --skip-duplicate -k ${{ secrets.NUGET }}
